name: Kiul-SMP-Utilities-V3
version: '${project.version}'
main: kiul.kiulsmputilitiesv3.KiulSMPUtilitiesV3
api-version: '1.21.11'
softdepend:
  - PattyEssentialsV3
commands:
  debug-event:
  logout:
    aliases:
      - safelog
  accessory:
    aliases:
      - equip
  give-accessory:
  debug-augment:
  toggle-sounds:
  test-crate:
  populate-crate:
  translate:
  give-ingredient:
  debug-waypoints:
  locator_bar:
  recaps:
  kmenu:
  spawn-crate:
  close-end: