name: Kiul-SMP-Utilities-V3
version: '${project.version}'
main: kiul.kiulsmputilitiesv3.KiulSMPUtilitiesV3
api-version: '1.21.4'
softdepend:
  - PattyEssentialsV3
commands:
  logout:
    aliases:
      - safelog
  accessory:
    aliases:
      - equip
  give-accessory:
  toggle-sounds:
  test-crate:
  populate-crate:
  translate:
  give-ingredient:
  recaps:
  kmenu:
  spawn-crate:
  close-end: